#!/bin/bash

#  Optimized MTL Federated Learning System - Complete Startup Script
# This script provides all commands needed to run the server and clients

echo " Optimized MTL Federated Learning System"
echo "=========================================="
echo ""
echo " Available Commands:"
echo ""

# Colors for better output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}1. Environment Setup:${NC}"
echo "   cd /home/pc/Documents/LAB/FedAvgLS/FedBERT-LoRA"
echo "   source venv/bin/activate"
echo ""

echo -e "${BLUE}2. Server Startup:${NC}"
echo -e "${GREEN}   python optimized_mtl_federated.py --mode server --rounds 5 --total_clients 3${NC}"
echo "   # Starts the MTL Federated Server on port 8771"
echo "   # Runs for 5 rounds, expects 3 clients"
echo ""

echo -e "${BLUE}3. Client Startup Commands:${NC}"
echo -e "${GREEN}   # Terminal 1 - Client 1:${NC}"
echo "   python optimized_mtl_federated.py --mode client --client_id client_1 --tasks sst2 qqp stsb"
echo ""
echo -e "${GREEN}   # Terminal 2 - Client 2:${NC}"
echo "   python optimized_mtl_federated.py --mode client --client_id client_2 --tasks sst2 qqp stsb"
echo ""
echo -e "${GREEN}   # Terminal 3 - Client 3:${NC}"
echo "   python optimized_mtl_federated.py --mode client --client_id client_3 --tasks sst2 qqp stsb"
echo ""

echo -e "${BLUE}4. Testing Commands:${NC}"
echo -e "${YELLOW}   # Test the optimized system:${YELLOW}"
echo "   python test_optimized_mtl.py"
echo ""
echo -e "${YELLOW}   # Run optimization demo:${YELLOW}"
echo "   python optimization_demo.py"
echo ""

echo -e "${BLUE}5. Alternative Server Commands:${NC}"
echo -e "${GREEN}   # Quick test (2 rounds, 2 clients):${NC}"
echo "   python optimized_mtl_federated.py --mode server --rounds 2 --total_clients 2"
echo ""
echo -e "${GREEN}   # Production run (10 rounds, 5 clients):${NC}"
echo "   python optimized_mtl_federated.py --mode server --rounds 10 --total_clients 5"
echo ""
echo -e "${GREEN}   # Custom configuration:${NC}"
echo "   python optimized_mtl_federated.py --mode server --rounds 3 --total_clients 3 --port 8772"
echo ""

echo -e "${BLUE}6. Alternative Client Commands:${NC}"
echo -e "${GREEN}   # Single task clients:${NC}"
echo "   python optimized_mtl_federated.py --mode client --client_id client_sst2 --tasks sst2"
echo "   python optimized_mtl_federated.py --mode client --client_id client_qqp --tasks qqp"
echo "   python optimized_mtl_federated.py --mode client --client_id client_stsb --tasks stsb"
echo ""
echo -e "${GREEN}   # Two-task clients:${NC}"
echo "   python optimized_mtl_federated.py --mode client --client_id client_clf --tasks sst2 qqp"
echo "   python optimized_mtl_federated.py --mode client --client_id client_reg --tasks stsb"
echo ""

echo -e "${BLUE}7. Monitoring Commands:${NC}"
echo -e "${YELLOW}   # Check system logs:${YELLOW}"
echo "   tail -f optimized_mtl_federated.log"
echo ""
echo -e "${YELLOW}   # Monitor server output:${YELLOW}"
echo "   # (Run in separate terminal after starting server)"
echo ""

echo -e "${BLUE}8. Cleanup Commands:${NC}"
echo -e "${YELLOW}   # Stop all processes:${YELLOW}"
echo "   pkill -f optimized_mtl_federated.py"
echo ""
echo -e "${YELLOW}   # Clean log files:${YELLOW}"
echo "   rm -f optimized_mtl_federated.log"
echo "   rm -rf no_lora_results/"
echo ""

echo -e "${BLUE}9. Complete Workflow Example:${NC}"
echo "   # Terminal 1 - Server:"
echo "   cd /home/pc/Documents/LAB/FedAvgLS/FedBERT-LoRA && source venv/bin/activate"
echo "   python optimized_mtl_federated.py --mode server --rounds 3 --total_clients 3"
echo ""
echo "   # Terminal 2 - Client 1:"
echo "   cd /home/pc/Documents/LAB/FedAvgLS/FedBERT-LoRA && source venv/bin/activate"
echo "   python optimized_mtl_federated.py --mode client --client_id client_1 --tasks sst2 qqp stsb"
echo ""
echo "   # Terminal 3 - Client 2:"
echo "   cd /home/pc/Documents/LAB/FedAvgLS/FedBERT-LoRA && source venv/bin/activate"
echo "   python optimized_mtl_federated.py --mode client --client_id client_2 --tasks sst2 qqp stsb"
echo ""
echo "   # Terminal 4 - Client 3:"
echo "   cd /home/pc/Documents/LAB/FedAvgLS/FedBERT-LoRA && source venv/bin/activate"
echo "   python optimized_mtl_federated.py --mode client --client_id client_3 --tasks sst2 qqp stsb"
echo ""

echo -e "${BLUE}10. Expected Output:${NC}"
echo "    Server: 'Starting optimized server on port 8771'"
echo "    Server: 'Waiting for clients... (0/1)'"
echo "    Client: 'Client client_1 registered successfully'"
echo "    Server: 'Starting training with X clients'"
echo "    All: Performance metrics and completion status"
echo ""

echo -e "${BLUE}11. Troubleshooting:${NC}"
echo "    If clients fail to connect:"
echo "      - Ensure server is running first"
echo "      - Check firewall settings"
echo "      - Verify port 8771 is available"
echo "      - Check system resources (RAM, CPU)"
echo ""
echo "    If training is slow:"
echo "      - Reduce --samples parameter"
echo "      - Use --rounds 2 for testing"
echo "      - Monitor system resources"
echo ""
echo "    If getting import errors:"
echo "      - Run: source venv/bin/activate"
echo "      - Check Python path"
echo "      - Verify all dependencies installed"
echo ""

echo -e "${BLUE}12. Performance Tips:${NC}"
echo "    Use SSD storage for better I/O performance"
echo "    Monitor RAM usage (each client ~500MB-1GB)"
echo "    Close unnecessary applications during training"
echo "    Use terminal multiplexer (tmux/screen) for multiple clients"
echo ""

echo " Happy Federated Learning! "
echo ""
echo "For more information, see:"
echo "   - OPTIMIZATION_REPORT.md"
echo "   - MTL_FEDERATED_IMPLEMENTATION.md"
echo "   - optimized_config.ini"
